name: Unzip rebuilt package

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Remove old files (except .github and ZIP)
        run: |
          shopt -s extglob
          rm -rf !(irisje_rebuilt.zip|.github)

      - name: Unzip rebuilt archive
        run: unzip irisje_rebuilt.zip -d .

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped rebuilt package" || echo "No changes"
          git push
