name: Unzip rebuilt package

on:
  workflow_dispatch:   # Handmatig starten via "Actions" â†’ "Run workflow"
  push:
    paths:
      - "irisje_rebuilt.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Remove old files (except ZIP & workflow)
        run: |
          shopt -s extglob
          rm -rf !(irisje_rebuilt.zip|.github)

      - name: Unzip rebuilt archive
        run: unzip irisje_rebuilt.zip -d .

      - name: Commit unzipped files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Unpacked rebuilt zip"
          git push
